dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - bc
    - mutt
    - mailutils
language: bash 

stages:
  - test
  - sonarscan
  - release
  
jobs:
  include:
    - stage: test
      before_install:
        - chmod +x ./src/testemail
      before_script:
      script:
        - bash ./src/testemail  
    
notifications:
  email:
    recipients:
      - kavitasanap@gmail.com
    on_success: never # default: change
    on_failure: never # default: always
 
 