dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - bc
    - mutt
    - mailutils
    - postfix
language: bash 

stages:
  - test
  - sonarscan
  - release
  
jobs:
  include:
    - stage: test
      before_install:
        - chmod +x ./src/testemail
      before_script:
        - sudo service postfix stop
        - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
        - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
        - sudo service postfix restart
        - sudo service sendmail restart
      script:
        - bash ./src/testemail  
    
notifications:
  email:
    recipients:
      - kavitasanap@gmail.com
    on_success: never # default: change
    on_failure: never # default: always
 
 