dist: trusty

addons:
  sonarcloud:
    organization: "kavitagithub" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

language: bash 

stages:
  - test
  - sonarscan
  - release
  
jobs:
  include:
    - stage: test
      before_install:
        - chmod +x ./src/app-monitor
      script:
        - bats test/bats
    - stage: sonarscan
      script: 
        - sonar-scanner
    - stage: release
      before_install:
        - chmod +x ./src/app-monitor
      before_script:
        before_script:
          - composer self-update -q
          - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
          - if [ -z "$dependencies" ]; then composer install; fi;
          - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
          - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
          - composer show -i
      script:
        - bash ./src/release
    
notifications:
  email:
    recipients:
      - kavitasanap@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
 
branches:
  only:
  - master