dist: trusty

addons:
  sonarcloud:
    organization: "kavitagithub" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

language: bash 

stages:
#  - test
#  - sonarscan
  - release
  
jobs:
  include:
    - stage: release
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq mutt
        - chmod +x ./src/app-monitoring
      script:
        - sh ./src/release.sh      
    
notifications:
  email:
    recipients:
      - kavitasanap@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
 
 