#!/bin/bash

echo "Merge master branch code to release branch"
git clone https://github.com/kavitasanap/app-monitor.git
cd app-monitor
git checkout release
git merge master
git push origin release
git checkout master