#!/bin/bash


BASE_DIR=`pwd`
html_report="${BASE_DIR}/report/monitoring_report_2018-01-21.html"
echo "test email in travis-ci ${html_report}"

email="kavitasanap@gmail.com"

curl --request POST \
  --url https://api.sendgrid.com/v3/mail/send \
  --header "Authorization: Bearer $SENDGRID_API_KEY" \
  --header 'Content-Type: application/json' \
  --data '{"personalizations": [{"to": [{"email": ${email}}]}],"from": {"email": {"kavitasanap@gmail"},"subject": "Sending with SendGrid is Fun","content": [{"type": "text/plain", "value": "and easy to do anywhere, even with cURL"}]}'
echo "finished email testing"